# Generated by Django 6.1.1 on 2026-09-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0002_kullanici_dogrulama_kodu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='premium_bitis',
        ),
    ]
