# Generated by Django 6.1.1 on 2026-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakim_modu_acik', models.BooleanField(default=False)),
                ('bakim_mesaji', models.CharField(default='Uygulama bakımda, birazdan döneceğiz.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=255)),
                ('mail_dogrulandi', models.BooleanField(default=False)),
                ('trial_baslangic', models.DateTimeField(auto_now_add=True)),
                ('trial_bitis', models.DateTimeField(blank=True, null=True)),
                ('premium_mi', models.BooleanField(default=False)),
                ('premium_bitis', models.DateTimeField(blank=True, null=True)),
                ('cihazlar', models.JSONField(blank=True, default=list)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
