# Generated by Django 6.1.1 on 2026-09-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_remove_kullanici_premium_bitis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='cihazlar',
        ),
        migrations.CreateModel(
            name='Cihaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cihaz_id', models.CharField(max_length=255)),
                ('marka', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cihazlar', to='kullanicilar.kullanici')),
            ],
        ),
    ]
