# Generated by Django 6.1.1 on 2026-09-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='dogrulama_kodu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
