# Generated by Django 6.1.1 on 2026-09-16 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0004_remove_kullanici_cihazlar_cihaz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayarlar',
            options={'verbose_name': 'Ayar', 'verbose_name_plural': 'Genel Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='cihaz',
            options={'verbose_name': 'Cihaz', 'verbose_name_plural': 'Cihazlar'},
        ),
        migrations.AlterModelOptions(
            name='kullanici',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='kullanici',
            name='dogrulama_kodu_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Kodu Zamanı'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='bakim_mesaji',
            field=models.CharField(default='Uygulama bakımda, birazdan döneceğiz.', max_length=255, verbose_name='Bakım Mesajı'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='bakim_modu_acik',
            field=models.BooleanField(default=False, verbose_name='Bakım Modu Açık'),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='cihaz_id',
            field=models.CharField(max_length=255, verbose_name='Cihaz Kimliği'),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cihazlar', to='kullanicilar.kullanici', verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='marka',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='dogrulama_kodu',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Doğrulama Kodu'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='mail_dogrulandi',
            field=models.BooleanField(default=False, verbose_name='E-posta Doğrulandı'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='premium_mi',
            field=models.BooleanField(default=False, verbose_name='Premium mi'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='sifre',
            field=models.CharField(max_length=255, verbose_name='Şifre'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='trial_baslangic',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Deneme Başlangıcı'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='trial_bitis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deneme Bitişi'),
        ),
    ]
