# Generated by Django 6.1.1 on 2026-09-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0005_dogrulama_kodu_zamani_ekle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Eklenme Tarihi'),
        ),
    ]
