# Generated by Django 6.1.1 on 2026-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0006_alter_cihaz_eklenme_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='basarisiz_giris_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='Başarısız Giriş Sayısı'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='kilit_bitis_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kilit Bitiş Zamanı'),
        ),
        migrations.AlterUniqueTogether(
            name='cihaz',
            unique_together={('kullanici', 'cihaz_id')},
        ),
    ]
