# Generated by Django 6.1.1 on 2026-09-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0007_kullanici_basarisiz_giris_sayisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='sifirlama_kodu',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Şifre Sıfırlama Kodu'),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='sifirlama_kodu_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Şifre Sıfırlama Kodu Zamanı'),
        ),
    ]
