# Generated by Django 6.1.1 on 2026-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0008_kullanici_sifirlama_kodu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='bakim_max_versiyon',
            field=models.PositiveIntegerField(blank=True, help_text='Bu versionCode ve altındaki uygulamalar bakım modundan etkilenir. Boş bırakılırsa tüm versiyonlar etkilenir.', null=True, verbose_name='Bakım Modu - Maksimum Versiyon (versionCode)'),
        ),
    ]
